# Generated by Django 4.2.2 on 2023-06-21 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="post_date",
            new_name="create_date",
        ),
        migrations.AddField(
            model_name="post",
            name="last_update_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="publish_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
