# Generated by Django 4.2.2 on 2023-06-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0002_rename_post_date_post_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
