# Generated by Django 4.2.2 on 2023-07-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts_app", "0003_alter_post_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="scheduled",
            field=models.BooleanField(default=False),
        ),
    ]
