# Generated by Django 4.2.2 on 2023-07-07 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="create_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="scheduled",
            new_name="is_scheduled",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="last_update_date",
            new_name="last_updated_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_owner",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="publish_date",
            new_name="publish_datetime",
        ),
    ]
