# Generated by Django 4.2.2 on 2023-07-07 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post_date",
            new_name="posted_at",
        ),
    ]
