# Generated by Django 4.2.2 on 2023-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_rename_post_date_comment_posted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_displayed",
            field=models.BooleanField(default=False),
        ),
    ]
